### ISSUE TITLE
Intermittent GIF Conversion Failures for WEBM Files

### ISSUE THREAD

**Issue by xwxYa** [laggykiller/sticker-convert#145]
I am experiencing issues with the sticker-convert project where only some of the WEBM files successfully convert to GIFs, while others fail during the conversion process. This inconsistency is causing significant usability issues, and I'm seeking assistance or a potential fix.

**Environment**
Operating System: Windows 11
Python Version: 3.12.3
Project Version: v2.8.6

**Steps to Reproduce**
Download [stickers](https://t.me/addstickers/Chillet_Palworld) from the Telegram.The files download successfully in WEBM format.
Initiated conversion of downloaded WEBM files to GIFs using the project's provided functionality.
Observed that only a subset of the files were successfully converted to GIFs. Others failed during the conversion process, mostly with errors related to file saving and unrecognized file extensions.

**Expected Behavior**
All WEBM files downloaded from the sticker set should convert to GIFs without errors.
**Actual Behavior**
Only some WEBM files convert successfully. Others fail with a recurring error:

**Logs and Error Messages**
```
Traceback (most recent call last):
  File "D:\software\sticker-convert\PIL\Image.py", line 2436, in save
KeyError: ''
ValueError: unknown file extension:
```
I would appreciate any guidance on resolving these conversion issues or any updates that might address this problem. Thank you for your support and for maintaining this useful project!

**Comment by laggykiller** [comment]
Thanks for reporting. Should be fixed in 2.8.7, please try.

Also note that there are more than two distinct alpha values in the stickers provided. As there can only be one color designated as transparent in GIF, the edges of the sticker would contain rough white pixels. You may either:
- Choose another `img-format` and `vid-format` (e.g. `.apng`)
- Set Background color (`bg_color`) in advanced compression option to `ffffffff` (Non-transparent background)
