### ISSUE TITLE
Hello, can you delete the kakao download method? Many people are making money from it by downloading emoticons and selling them for a fee.

### ISSUE THREAD

**Issue by luckyyaa** [laggykiller/sticker-convert#163]

**Comment by laggykiller** [comment]
Please refrain from making multiple issues on the wrong repo.

**Comment by laggykiller** [comment]
(I would assume you are a dev from KakaoCorp?)

I feel sorry for the headache brought by this problem, and I absolutely feel your anger that someone is profiting on others hardwork and copyright. However, I think you should be going after those who are selling emoticons, not the programmer. Keping this repo up for free with sourcecode is actually doing good to KakaoCorp:

1. Of course there would be people attempting to make a profit from free things, but I doubt those people who are selling emoticons actually make profit. A normal person would find free tools like this before they consider buying stickers from black market.
2. Even if I remove Kakao download method, someone else would still figure out how to download emoticons from Kakao. Could be done by screencapping, could be writing program. This is a never ending cat-and-mouse game. The degenerates combined have practically unlimited time, brainpower and resources to download emoticons, but KakaoCorp's dev has limited time, and time spent on playing this futile game could had been used on developing other things that actually bring profit to the company.
3. If my repo is shutdowned, someone else who might even be smarter than me would write program to download stickers from Kakao. They may close-source it and sell the program itself. Heck, they may even add some malware to the mix and even stealing credentials. Now, not only those who are buying emoticons from unauthorized sellers are harmed, people who buy those close-sourced programs would be harmed financially or even cause security issue.
4. The presence of this repo is a harm reduction for those who wants to download Kakao emoticon. Let's imagine someone who is desperate to download Kakao emoticons, even if it means paying money. They would search on Google "download kakao emoticon". If this repo exists, they would download my tool and get the job done for free and safely. If my repo is gone, they would find those Chinese shopping websites instead and get their money sucked. By restricting something, you are just pushing that thing to the underground and promote the black market.

**Comment by laggykiller** [comment]
@luckyyaa For one last time, please stop creating new issues on different repo. Keep the conversation here. Use the comment box to send your reply.

I appreciate that you stand out for me, and I share your anger that the opensource project is being abused by the sellers in China. However the decision remains that I would not take the functionality down.

- There is no evidence that they are earning by using sticker-convert. They could be doing their own research.
- Even if they are using sticker-convert, we can't let the greater majority of users suffer from broken program due to the action of those minority. Linux is also a FOSS project that some people try to sell it to others with minimal effort (e.g. Some Windows-skinned linux distros), this does not mean Linus Torvalds should take down Linux because someone is leaching off his hardwork.

> Is there any way to prevent Chinese people from using it?

Potential solutions:
- IP blocking, but I cannot restrict people from visiting my GitHub repo based on network location, and those Chinese are using a VPN anyway so it is futile from the start.
- I could check network location on program launch, but again they could use VPN, plus this feels too intrusive and harming normal unsuspecting users.
- Publicly name and shame them until they regain their basic human ability to feel shame.
- Report those people to shopping website and Chinese authority.

**Comment by laggykiller** [comment]
@luckyyaa May I get a list of those Chinese forums? Thank you.

**Comment by laggykiller** [comment]
Who is 'she'? Are you trying not to mention the identity of those people, fearing reprecussions? You may contact me via email about that.

> those who asked you to repair and download Kakao emoticons are the sellers

No that didn't happen. Nobody pointed out to me that downloading Kako emoticons was broken and asked me for fixing. I discovered because I felt suspicious that my repo got mentioned on Kakao's internal wiki and tests are failing.

> why do this?

Because I feel like a tool should exist.

**Comment by laggykiller** [comment]
You can find it on pypi
