### ISSUE TITLE
Offer AppImage instead of Docker for Linux

### ISSUE THREAD

**Issue by zilti** [laggykiller/sticker-convert#37]
Docker is not a package manager, and supplying such a tool as docker image is wrong, to be very diplomatic.

**Comment by laggykiller** [comment]
I intended the Docker image for running in CLI, allowing use cases like batch conversion and perhaps making a bot for converting stickers. But yes in most case it does not make sense.

Creating appimage is not an easy task when compared with creating docker image. I have tried to create appimage for this project before but failed.

I tried to create appimage again, this time using `appimage-builder`. You can see my commit here: https://github.com/laggykiller/sticker-convert/commit/92317c02c5d0f894b900cd142474f0a323628416

The build instruction is stored in https://github.com/laggykiller/sticker-convert/blob/master/AppImageBuilder.yml

The resulting appimage should work with CLI mode. However due to trouble in packing `ttkbootstrap`, GUI mode is not working, throwing the following error:

```
Traceback (most recent call last):
  File "/tmp/.mount_appima9ASyip/usr/src/main.py", line 3, in <module>
    root = ttk.Window(themename='darkly')
  File "/tmp/.mount_appima9ASyip/usr/lib/python3.8/site-packages/ttkbootstrap/window.py", line 279, in __init__
    self._style = Style(themename)
  File "/tmp/.mount_appima9ASyip/usr/lib/python3.8/site-packages/ttkbootstrap/style.py", line 489, in __init__
    localization.initialize_localities()
  File "/tmp/.mount_appima9ASyip/usr/lib/python3.8/site-packages/ttkbootstrap/localization/msgs.py", line 9, in initialize_localities
    m.initialize()
  File "/tmp/.mount_appima9ASyip/usr/lib/python3.8/site-packages/ttkbootstrap/localization/msgs.py", line 27, in initialize
    MessageCatalog.set_many(self.locale, *messages)
  File "/tmp/.mount_appima9ASyip/usr/lib/python3.8/site-packages/ttkbootstrap/localization/msgcat.py", line 142, in set_many
    return int(root.tk.eval(out))
_tkinter.TclError: invalid command name "::msgcat::mcmset"
```

I have created a bug report in ttkbootstrap repo with more detail: https://github.com/israel-dryer/ttkbootstrap/issues/470

Side note, if you don't want to use docker, you can run the python script directly by following this instruction: https://github.com/laggykiller/sticker-convert/blob/master/docs/COMPILING.md

**Comment by laggykiller** [comment]
I am now using an older version of ttkbootstrap in appimage to make the GUI work in appimage.

Go and test v1.16.0

https://github.com/laggykiller/sticker-convert/releases

**Comment by laggykiller** [comment]
Closing for now. Please open another issue if there is any other problem with appimage.

**Comment by laggykiller** [comment]
Unfortunately those python-specific tools would not be suitable for packaging this project, as you can see my project uses quite a number of external programs like ImageMagick, ffmpeg, apngasm, apngdis, pngquant...
