### ISSUE TITLE
Animations play slower after converting from .tgs to .apng

### ISSUE THREAD

**Issue by azuredusk10** [laggykiller/sticker-convert#4]
I converted [this Telegram sticker set](https://telegram.me/addstickers/ColoredCats) to .apng for use with Signal, however the animations in the converted stickers play more slowly than the originals.

[Video recording of original Telegram stickers in Telegram for iOS](https://streamable.com/bhoc88)

[Video recording of the converted .apng stickers in Signal Desktop](https://streamable.com/yw9zf4)

You can see that the converted files play about half as quickly as the originals, making it look like the stickers are moving in slow motion.

Steps to reproduce:
1. Convert the ["Colored Cats" Telegram sticker pack](https://telegram.me/addstickers/ColoredCats) to Signal .apng in a local directory, using the following settings. This step took a long time, so you can also [download a few of the converted .apng files here](https://filetransfer.io/data-package/NuqLu994#link) for 21 days.
<img width="691" alt="Screenshot 2022-12-29 at 00 17 46" src="https://user-images.githubusercontent.com/18142893/209887597-9b5982f8-4aa2-45fe-917d-a9dc33d16bca.png">

2. Open Signal Desktop's sticker pack creator (File > Create/upload sticker pack)

3. Drag the converted .apng files into Signal Desktop's sticker pack creator.

Is this due to the settings I've used or could this be a bug in the conversion process?

Thanks

**Comment by laggykiller** [comment]
Thank you for your report

The slow animation is caused by tgs is handled by converting to webp first, which the fps is not written properly into webp file or cannot be read by ImageMagick. To fix this, tgs is now handled by converting into png files first, then use ffmpeg to generate final file with input fps specified.

Please check if v1.6.0 works for you

For long conversion time of apng, this is on my TODO list

It also seems like the resulting image is glitched, I have opened a bug report upstream: https://gitlab.com/mattbas/python-lottie/-/issues/99

btw the sticker pack url should be `https://telegram.me/addstickers/ColoredCats` not `https://telegram.me/addstickers/ColoredCat`.

**Comment by azuredusk10** [comment]
This fixes the issue, thank you! The converted .apng files now play with the same fps as the input .tgs file. 

I've left a comment in issue #5 about the visual glitches.

Thank you for your help, the tool is shaping up really nicely and I've enjoyed trying it out. Let me know if there's anything I can help test.
