### ISSUE TITLE
animation converted from tgs using python-lottie may produce corrupted image

### ISSUE THREAD

**Issue by laggykiller** [laggykiller/sticker-convert#5]
Discovered from: https://github.com/laggykiller/sticker-convert/issues/4

An issue is opened upstream: https://gitlab.com/mattbas/python-lottie/-/issues/99

**Comment by azuredusk10** [comment]
I noticed this when converting the "Colored Cats" Telegram sticker pack to .apng.

Like you've already reported upstream, I noticed that about half of the stickers from that sticker pack had visual glitches where some of the layers weren't rendered in the converted file. I've attached a couple of examples below.

**Original:**
![IMG_A637B3E4BC7D-1](https://user-images.githubusercontent.com/18142893/210017478-f3af881d-b0e4-4fde-9258-c4330c451e72.jpeg)

![IMG_055DDDCAD3EA-1](https://user-images.githubusercontent.com/18142893/210017105-8750b361-9910-4e84-9a01-17a54e1e975a.jpeg)


**Converted, with missing layers:**
<img width="191" alt="Screenshot 2022-12-29 at 22 34 27" src="https://user-images.githubusercontent.com/18142893/210017493-07ad2605-88ea-49d8-8c00-4d5f9df28086.png">

<img width="192" alt="Screenshot 2022-12-29 at 22 26 08" src="https://user-images.githubusercontent.com/18142893/210017134-3f7a2a45-b12e-4094-9732-2f40a72b2062.png">

Hopefully the upstream are able to look into it sometime in the future.

Thanks for reporting this and for all your help.

**Comment by laggykiller** [comment]
I have written [rlottie-python](https://github.com/laggykiller/rlottie-python), which provides ctypes binding to librlottie for rendering tgs animation to bitmaps. It should be more reliable than `lottie` python module.

> v1.8.0 now uses rlottie-python for converting tgs to bitmaps image / animation.

@azuredusk10 you may have a try

https://github.com/laggykiller/sticker-convert/releases

**Comment by azuredusk10** [comment]
From my initial testing, this bug looks fixed. The converted stickers don't have any visual corruptions, and also, they are compressed at a higher quality. 

I converted the same "Colored Cats" sticker pack from .tgs to .apng for Signal, changing the minimum acceptable fps in the Signal preset to 15. Previously when I did this, the conversion failed for most stickers because the filesize was too large. However, this time, none of the stickers failed. The animations in the converted stickers were super smooth and the resolution and colours looked brilliant.

I'd recommend changing the Signal preset so that the minimum accepted fps is higher. For me, a minimum acceptable fps of 15 worked well, while the default value of 1 produced some very choppy animations.

With a minimum fps of 15, the tool lowered the resolution more than the frame rate in order to compress the image. Our eyes are more sensitive to frame rates than image resolutions, so an animation with a higher frame rate and a lower resolution will look better to most people than the same animation with a higher resolution and a lower frame rate. 

I'll convert a few more Telegram stickers with minimum fps set to 15 and see how it goes.

For your reference, here is the [converted "Colored Cats" sticker pack](https://signal.art/addstickers/#pack_id=2ef10d945db55e0712773e18b24febe0&pack_key=738e63dab9b90cb91f7105421d32fde024c33d7b4a51836d90dba1954da3d600). 
_Signal present, modified so that the minimum fps was 15. 
6 steps._

Incredible, incredible work. Can't wait to convert some more packs with this. Thank you!
